[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
askama_axum = "0.3.0"
axum = "0.6.20"
itertools = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio", "sqlite"] }
